querypatient: main.o addPatient.o agematch.o minmaxagematch.o purduematch.o readinput.o readpatientrec.o
	gcc -o querypatient main.o addPatient.o agematch.o minmaxagematch.o purduematch.o readinput.o readpatientrec.o
main.o: main.c header.h
	gcc -c main.c
addPatient.o: addPatient.c header.h
	gcc -c addPatient.c
agematch.o: agematch.c header.h
	gcc -c agematch.c
minmaxagematch.o: minmaxagematch.c header.h
	gcc -c minmaxagematch.c
purduematch.o: purduematch.c header.h
	gcc -c purduematch.c
readinput.o: readinput.c header.h
	gcc -c readinput.c
readpatientrec.o: readpatientrec.c header.h
	gcc -c readpatientrec.c