calchamming: main.o calcdiff.o calchamm2.o readinput2.o write1Darray.o
	gcc -o calchamming main.o calcdiff.o calchamm2.o readinput2.o write1Darray.o
main.o: main.c mycpp.h myglobal.h header.h
	gcc -c main.c
calcdiff.o: calcdiff.c mycpp.h myglobal.h header.h
	gcc -c calcdiff.c
calchamm2.o: calchamm2.c mycpp.h myglobal.h header.h
	gcc -c calchamm2.c
readinput2.o: readinput2.c mycpp.h myglobal.h header.h
	gcc -c readinput2.c
write1Darray.o: write1Darray.c mycpp.h myglobal.h header.h
	gcc -c write1Darray.c
